services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dripple_db
      POSTGRES_USER: dripple_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dripple_user -d dripple_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache and Message Broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dripple_user:password@postgres:5432/dripple_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FFMPEG_PATH=ffmpeg
      - FFPROBE_PATH=ffprobe
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./assets:/app/assets
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    build: .
    command: celery -A app.config.celery_config worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://dripple_user:password@postgres:5432/dripple_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FFMPEG_PATH=ffmpeg
      - FFPROBE_PATH=ffprobe
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./assets:/app/assets
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Beat Scheduler
  celery-beat:
    build: .
    command: celery -A app.config.celery_config beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://dripple_user:password@postgres:5432/dripple_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FFMPEG_PATH=ffmpeg
      - FFPROBE_PATH=ffprobe
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./assets:/app/assets
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # pgAdmin Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@droplink.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
      - ./processed:/var/www/processed
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
