"""Add ProcessedVideo table

Revision ID: 0001
Revises: 
Create Date: 2025-09-18 02:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_videos',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('original_video_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('fps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('processing_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['original_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_videos')
    # ### end Alembic commands ###
